/*---------------------------------------------------------------------------------------------
 *  F13: 会话自动命名 — 纯前端启发式（无 LLM 依赖、零成本、<1ms）。
 *
 *  策略（参考 Claude Code / Codex CLI 的命名思路，但完全本地化）：
 *    1. 取第一句话（按 \n、。？！?!. 切分）
 *    2. 迭代去除中英文常见客套前缀（"帮我"、"请"、"能不能"、"Help me"…）
 *    3. 按 CJK / 非 CJK 限长（14 中文字 / 50 英文字符）
 *    4. 完全无内容 → fallback 到 "新会话 MM-DD HH:mm"
 *
 *  在 App.tsx 的 send() 内，检测 messages().length === 0 且 session.title === "新会话"
 *  时调用，结果通过 SDK c.renameSession 写回 sidecar；失败 silent 不影响发消息。
 *--------------------------------------------------------------------------------------------*/

/** 中英文常见客套词前缀（按出现频率 + 长度排，按出现顺序匹配） */
const PREFIXES: string[] = [
	// 中文 — 长前缀优先（避免短前缀先匹配吃掉部分）
	'能不能帮我', '可以帮我', '能帮我', '我想要', '我希望',
	'帮我做一个', '帮我做下', '帮我做', '帮我看下', '帮我看一下', '帮我看', '帮我写一个', '帮我写下', '帮我写', '帮我改下', '帮我改一下', '帮我改', '帮我修下', '帮我修', '帮我查', '帮我分析下', '帮我分析', '帮我整理', '帮我设计', '帮我',
	'做一个', '做一下', '做下',
	'看一下', '看下', '检查一下', '检查下', '分析一下', '分析下', '排查一下', '排查下',
	'请你', '请帮我', '请', '麻烦你', '麻烦',
	'能否', '能不能', '可不可以', '可以',
	'我想', '想要', '想',
	// 英文
	'Please ', 'pls ', 'Can you ', 'Could you ', 'Would you ', 'Help me ', 'I want to ', 'I need to ', 'I would like to ',
];

/** 把一段用户输入压缩成会话标题（< 14 中文字 / < 50 英文字符） */
export function smartTitleFromMessage(msg: string): string {
	if (!msg) return fallbackTitle();

	// 1. 取首句（任意行结束符 / 句末标点）
	let line = msg.split(/[\n\r。？！?!.]/)[0].trim();
	if (!line) return fallbackTitle();

	// 2. 迭代去前缀（"帮我请帮忙看下…" 这种叠词）
	const lower = (s: string): string => s.toLowerCase();
	let changed = true;
	let guard = 0;
	while (changed && guard++ < 10) {
		changed = false;
		for (const p of PREFIXES) {
			if (lower(line).startsWith(lower(p))) {
				line = line.slice(p.length).trim();
				changed = true;
				break;
			}
		}
	}

	if (!line) return fallbackTitle();

	// 3. 限长
	const isCJK = /[一-龥　-〿]/.test(line);
	const maxLen = isCJK ? 14 : 50;
	if (line.length > maxLen) {
		line = line.slice(0, maxLen).trimEnd() + '…';
	}

	// 4. 太短的（清洗后只剩 1 个字符 / 标点）→ fallback
	if (line.length < 2) return fallbackTitle();

	return line;
}

/**
 * 判断一个 title 是否是**自动生成的**默认名（可被 autoName 覆盖）。
 *
 * maxian 当前有多种默认名格式（散落在多处 createSession 调用 + sidecar 后端）：
 *   - "新会话" / "新对话"（sessionManager.ts:428 后端默认）
 *   - "会话 10:36"（前端 Code 模式 createSession）
 *   - "对话 10:37"（前端 Chat 模式 createSession）
 *   - "新会话 05-30 10:30"（本文件 fallbackTitle）
 *
 * 凡是匹配以上格式之一 → 视为可被自动覆盖；其它（含用户手改）→ 保留不动。
 */
export function isAutoGeneratedTitle(t: string | undefined | null): boolean {
	if (!t) return true;
	if (t === '新会话' || t === '新对话') return true;
	if (/^(会话|对话)\s\d{1,2}:\d{2}$/.test(t)) return true;
	if (/^新(会话|对话)\s\d{2}-\d{2}\s\d{2}:\d{2}$/.test(t)) return true;
	return false;
}

/** 兜底：以日期时间为名（避免又叫"新会话"覆盖默认值无意义） */
function fallbackTitle(): string {
	const d = new Date();
	const mm = String(d.getMonth() + 1).padStart(2, '0');
	const dd = String(d.getDate()).padStart(2, '0');
	const HH = String(d.getHours()).padStart(2, '0');
	const MM = String(d.getMinutes()).padStart(2, '0');
	return `新会话 ${mm}-${dd} ${HH}:${MM}`;
}
